🙈  (deps) @jeromefitz/lint-staged [b] (#2312)
No longer necessary here either. 🪦

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -19,5 +19,10 @@ if [ "$HUSKY" = "0" ]; then
 fi
 
 if [ ! "$HUSKY__PRE_COMMIT__LINT_STAGED" = "0" ]; then
-    pnpm lint-staged
+    if git status --short | grep --quiet '^MM'; then
+        printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
+        exit 1;
+    fi
+    pnpm exec biome check --write --staged --no-errors-on-unmatched --files-ignore-unknown=true
+    git update-index --again
 fi
